version: '3'

services:
  frontend:
    build: ./frontend
    command: npm run start
    restart: unless-stopped
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    command: npm run dev
    restart: unless-stopped
    ports:
      - "5000:5000"
      